version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      #- .:/code
      - .:/app # Cambiado para que coincida con el WORKDIR en el Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings


  redis:
    image: redis:7
    ports:
      - "6379:6379"
