# Generated by Django 5.2.6 on 2025-09-18 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='diagrams.diagram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
