# Generated by Django 5.2.6 on 2025-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_remove_diagram_updated_at_alter_diagram_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
